### ISSUE TITLE
Create Empty 2.13 Artifact

### ISSUE THREAD

**Issue by NthPortal** [bigwheel/util-backports#3]
Could you create an empty 2.13 artifact, so that:

- people who cross-build 2.12 and 2.13 don't need to worry about adding conditional logic about when to add the dependency
- it can be used in (ammonite) scripts which support both 2.12 and 2.13

**Comment by bigwheel** [comment]
It seems like a good idea to me.
But unfortunately I'm not working with Scala now therefore no big motivation to do it.
I may do it but I cannot promise its day.

PR welcome.
